---
title: "Basic analysis of the dots stimulus"
output:
  html_notebook:
    toc: true
    code_folding: hide
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: Adrian Radillo
---

Load required libraries
```{r}
library(data.table)
library(ggplot2)
```
Load a data file
```{r}
dataTag <- "detail_8"
datafile <- paste("../data/",dataTag,".csv",sep='')
data <- fread(file=datafile, header=TRUE, sep=",")
# uncomment next line to inspect data table
str(data)
```
# Stimulus used in this script
[Tag](https://github.com/aernesto/dotsStimExperiments/releases) name: **`r dataTag`**.  
Parameters of dots stimulus:  
```{r}
library(knitr)
vals <- c(1,5,10,1,0,0,3,0,70,500,1,0)  
params <- c("stencilNumber",
            "pixelSize", 
            "diameter",  
            "speed",
            "yCenter",  
            "xCenter", 
            "density",  
            "direction",
            "coherence",  
            "dotsDuration", 
            "randSeedBase", 
            "coherenceSTD")
dotsParam <- data.table(par= params, val = vals)
kable(dotsParam, format='html', align = c('l','c'), digits = 0,
      col.names = c("par","val"))
```

# Basic questions
## 1. Frame number 
```{r}
axes_labels_font <- 18
axes_font <- 15

ggplot(data, aes(x=frameIdx,y=onsetFrame)) +
  geom_line(size=.2) +
  geom_point(aes(col=factor(isTight)),size=2) +
  labs(title="snow-dots frame vs. sequential order",
         subtitle=paste("From",dataTag,"dataset",sep=" "),
         y="'onsetFrame' by snow-dots",
         x="frame index in sequence",
         color="isTight") + theme(plot.title=element_text(size=20,
                                    family="American Typewriter",
                                    color="tomato",
                                    lineheight=1.2),  # title
            plot.subtitle=element_text(size=15,
                                       family="American Typewriter"),  # subtitle
            plot.caption=element_text(size=15),  # caption
            axis.title.x=element_text(size=axes_labels_font),  # X axis title
            axis.title.y=element_text(size=axes_labels_font),  # Y axis title
            axis.text.x=element_text(size=axes_font),  # X axis text
            axis.text.y=element_text(size=axes_font))  # Y axis text
```
Histogram of 'skipped' frames:

```{r}
skipSize <- diff(unique(data$onsetFrame)) - 1 # subtract 1 as no frame is skipped if skipSize = 1
offset <- 0.5
hist(skipSize, breaks = seq(from = min(skipSize) - offset, to = max(skipSize) + offset, by = 1), 
     right = FALSE)
```


## 2. Frame durations  
```{r}
frameDurations <- data[,.(frameDur=onsetTime-swapTime), by=frameIdx]
ggplot(frameDurations, aes(x=frameIdx,y=frameDur)) +
  geom_line(size=.2) +
  geom_point(size=2) +
  labs(title="frame durations in sequential order",
         subtitle=paste("From",dataTag,"dataset",sep=" "),
         y="swapTime(n) - onsetTime(n)",
         x="frame index in sequence") + theme(plot.title=element_text(size=20,
                                    family="American Typewriter",
                                    color="tomato",
                                    lineheight=1.2),  # title
            plot.subtitle=element_text(size=15,
                                       family="American Typewriter"),  # subtitle
            plot.caption=element_text(size=15),  # caption
            axis.title.x=element_text(size=axes_labels_font),  # X axis title
            axis.title.y=element_text(size=axes_labels_font),  # Y axis title
            axis.text.x=element_text(size=axes_font),  # X axis text
            axis.text.y=element_text(size=axes_font))  # Y axis text
```

## 3. Frame by frame analysis  
We display the dots with their normalized position
```{r, fig.height=20, fig.width=20}
totFrames <- data[,max(frameIdx)]
numFramesToPlot <- totFrames
g <- ggplot(data[frameIdx < numFramesToPlot+1], aes(x=xpos, y=ypos)) +
  geom_point(aes(col=frameIdx),size=6) + xlim(0,1) + ylim(0,1)
# Add Title and Labels
g + coord_fixed() +  # coord_fixed is to get square aspect
    labs(title=paste("Dots from first ",numFramesToPlot," frames",sep = ''),
         subtitle=paste("From",dataTag,"dataset",sep=" "),
         y="normalized ypos",
         x="normalized xpos",
         color="frame") + 
    theme(plot.title=element_text(size=40,family="American Typewriter",
                                color="tomato", lineheight=1.2),  # title
        plot.subtitle=element_text(size=30, family="American Typewriter"),  # subtitle
        plot.caption=element_text(size=30),  # caption
        axis.title.x=element_text(size=2*axes_labels_font),  # X axis title
        axis.title.y=element_text(size=2*axes_labels_font),  # Y axis title
        axis.text.x=element_text(size=2*axes_font),  # X axis text
        axis.text.y=element_text(size=2*axes_font),  # Y axis text
        legend.text=element_text(size=1.5*axes_font),
        legend.title=element_text(size=1.5*axes_font))
```
```{r, fig.height=20, fig.width=20}
totFrames <- data[,max(frameIdx)]
numFramesToPlot <- 6#totFrames
g <- ggplot(data[frameIdx < numFramesToPlot+1], aes(x=xpos, y=ypos)) +
  geom_point(aes(shape=factor(frameIdx),col=frameIdx),size=6, stroke=2) +
  scale_shape_manual(values=c(3, 0, 2, 1, 4, 5)) + # refs for shapes: http://www.sthda.com/english/wiki/ggplot2-point-shapes  &   https://stackoverflow.com/a/34361768
  xlim(0,1) + ylim(0,1)
# Add Title and Labels
g + coord_fixed() +
  labs(title=paste("Dots from first ",numFramesToPlot," frames",sep = ''),
         subtitle=paste("From",dataTag,"dataset",sep=" "),
         y="normalized ypos",
         x="normalized xpos",
         color="frame", shape="frame") + 
  theme(plot.title=element_text(size=40,family="American Typewriter",
                                color="tomato", lineheight=1.2),  # title
        plot.subtitle=element_text(size=30, family="American Typewriter"),  # subtitle
        plot.caption=element_text(size=30),  # caption
        axis.title.x=element_text(size=2*axes_labels_font),  # X axis title
        axis.title.y=element_text(size=2*axes_labels_font),  # Y axis title
        axis.text.x=element_text(size=2*axes_font),  # X axis text
        axis.text.y=element_text(size=2*axes_font),  # Y axis text
        legend.text=element_text(size=1.5*axes_font),
        legend.title=element_text(size=1.5*axes_font))
```
